name: frames2art
favicon: null
layout_spectrum: 0.7182904535438865
typography_spectrum: 0.709807115374133
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7670317469164729
  lightness: 0.7246931137051433
  saturation: 0.2936290833167732
  rhythmicContrast: 0.2559217631351203
purpose: []
